### ISSUE TITLE
Kernel Panic few seconds after opening the game with BO3MacFix on Sequoia

### ISSUE THREAD

**Issue by adamwawrzynkowski** [InvoxiPlayGames/BO3MacFix#17] opened 2024-09-21 19:05 UTC
Hey,
The game is causing macOS GPUDrawer Kernel Panic with a fix applied on macOS Sequoia. I rolled back to Sonoma, and everything is working correctly.

I don't have logs, unfortunately (because of the macOS downgrade), but I believe you can debug this on your end.

**Comment by InvoxiPlayGames** [comment] 2024-09-21 19:11
What Mac are you trying this on, and if Intel, what GPU? I do not have macOS Sequioa yet, so I can't debug this on my end unfortunately.

If it still happens both with and **without** the fix, bugs like this that stop you from playing the game outright should definitely be reported to Activision/Aspyr or Apple (depending on where the blame lies), it's their responsibility to fix it.

**Comment by adamwawrzynkowski** [comment] 2024-09-21 19:18
> What Mac are you trying this on, and if Intel, what GPU? I do not have macOS Sequioa yet, so I can't debug this on my end unfortunately.

I'm using Mac Studio with M1 Max (32c GPU, 32GB RAM)

> If it still happens both with and **without** the fix, bugs like this that stop you from playing the game outright should definitely be reported to Activision/Aspyr or Apple (depending on where the blame lies), it's their responsibility to fix it.

This problem is present only when you apply the fix, without it - the game is launching correctly (but it's unplayable because of server connection issues lol, so your fix is 100% needed).

Kernel Panic is also always present (it's not random), and always on the Treyarch logo at the start. I thought I will post it here because Acti/Aspyr doesn't give a shit about BO3 on Mac :D

**Comment by anonnyanon** [comment] 2024-09-27 20:52
Same for me. Game will not launch at all. Sequoia 15.1 Beta. Game will launch without this fix applied

**Comment by FillItWithWok** [comment] 2024-10-01 16:31
Had to reinstall BO3 while on Sequoia and the game won't launch. Was working on Sonoma

**Comment by InvoxiPlayGames** [comment] 2024-10-21 10:15
I can't reproduce the kernel panic issue on Sequoia 15.0.1 on an M1 Pro MacBook Pro. Do you still have this issue on the latest macOS release version?

(Game not launching is another problem)

**Comment by InvoxiPlayGames** [comment] 2024-12-24 22:42
Since I still can't replicate the issue and the upcoming v1.1 fixes the one issue with the patch that could even remotely be causing this (albeit very unlikely), I'm gonna close this issue. Feel free to re-open if you're still having problems.

**Closed by InvoxiPlayGames** 2024-12-24 22:42 UTC
